---
title: "Exploring Difference in Difference Estimator Behavior Under Different Settings"
author: "Zheyuan Liu, Haoming Yang"
date: "4/16/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tidyr)
library(patchwork)
set.seed(640)
```

# Simulation

## Simulate Binary Outcome
```{r}
inverse_logit = function(logit) {
  return (exp(logit)/(1+exp(logit)))
}
```

$$
\begin{gather*}
Y \sim Bernoulli (p) \\
l = \alpha + \gamma G + \delta_t t + \tau D + \beta x + \epsilon \\
p = \frac{e^{l}}{1+e^{l}}
\end{gather*}
$$

```{r}
# Binary Timepoint
t = c(0,1)
# Binaray Treatment
treatment = c(0,1)
n_control = 1000
n_treat = 300

# Simulate X
x_binary = list(rnorm(n_control, 0, 1), rnorm(n_treat, 0, 1))

# Simulate coefficients
alpha_binary = 2# rnorm(1,0,1)
gamma_binary = -1.5# rnorm(1,0,1)
delta_t_binary = -1.5#rnorm(1,0.2,1)
tau_binary = 1#rnorm(1,0.2,1)
beta_binary = 0.5# rnorm(1,0,1)

# Simulate logit l 
error = rnorm(n_control, 0, 0.5)
logit_before_untreat = alpha_binary + gamma_binary*treatment[1] + delta_t_binary*t[1] + 
  tau_binary*t[1]*treatment[1] + beta_binary*x_binary[[1]] + error

error = rnorm(n_treat, 0,  0.5)
logit_before_treat = alpha_binary + gamma_binary*treatment[2] + delta_t_binary*t[1] + 
  tau_binary*t[1]*treatment[2] + beta_binary*x_binary[[2]] + error

error = rnorm(n_control, 0,  0.5)
logit_after_untreat = alpha_binary + gamma_binary*treatment[1] + delta_t_binary*t[2] + 
  tau_binary*t[2]*treatment[1] + beta_binary*x_binary[[1]] + error

error = rnorm(n_treat, 0,  0.5)
logit_after_treat = alpha_binary + gamma_binary*treatment[2] + delta_t_binary*t[2] + 
  tau_binary*t[2]*treatment[2] + beta_binary*x_binary[[2]] + error

# No tau term because treatment = 0 for both groups
# simulate parallel trend
logit_after_treat_para = alpha_binary + gamma_binary*treatment[2] + delta_t_binary*t[2] +
  beta_binary*x_binary[[2]] + error
```

```{r}
# visualization
df_logit = data.frame(treatment = c(rep(0, n_control), rep(1, n_treat)),
                      logit_before = c(logit_before_untreat, logit_before_treat),
                      logit_after = c(logit_after_untreat, logit_after_treat))

p1 = ggplot(df_logit, aes(x=logit_before, color=factor(treatment))) +
  geom_point(aes(y=logit_after)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  labs(color = "Group", x="Logit(P) Before", y="Logit(P) After", title="A")

df_p = data.frame(treatment = c(rep(0, n_control), rep(1, n_treat)),
                      p_before = inverse_logit(c(logit_before_untreat, logit_before_treat)),
                      p_after = inverse_logit(c(logit_after_untreat, logit_after_treat)))

p2 = ggplot(df_p, aes(x=p_before, color=factor(treatment))) +
  geom_point(aes(y=p_after)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  labs(color = "Group", x="Probability Before", y="Probability After", title="B")

df_avg_logit = data.frame(t = t,
                          logit_untreat = c(mean(logit_before_untreat), mean(logit_after_untreat)), 
                          logit_treat = c(mean(logit_before_treat), mean(logit_after_treat)),
                          logit_treat_para = c(mean(logit_before_treat), mean(logit_after_treat_para)))
p3 = ggplot(df_avg_logit, aes(x = t))+
  geom_line(aes(y=logit_untreat, color="Control")) + 
  geom_point(aes(y=logit_untreat)) +
  geom_line(aes(y=logit_treat, linetype="Actual", color="Treatment")) + 
  geom_point(aes(y=logit_treat)) + 
  geom_line(aes(y=logit_treat_para, linetype="Projection", color="Treatment")) +
  geom_point(aes(y=logit_treat_para)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  scale_linetype_manual(values=c("solid", "dashed"), labels=c("Actual", "Projection")) + 
  labs(color = "Group", linetype="Assumption", x="Time(0,1)", y="Logit(P)", title="C")

df_avg_p = data.frame(t = t,
                          p_untreat = inverse_logit(c(mean(logit_before_untreat), mean(logit_after_untreat))), 
                          p_treat = inverse_logit(c(mean(logit_before_treat), mean(logit_after_treat))),
                          p_treat_para = inverse_logit(c(mean(logit_before_treat), mean(logit_after_treat_para))))
p4 = ggplot(df_avg_p, aes(x = t))+
  geom_line(aes(y=p_untreat, color="Control")) + 
  geom_point(aes(y=p_untreat)) +
  geom_line(aes(y=p_treat, linetype="Actual", color="Treatment")) + 
  geom_point(aes(y=p_treat)) + 
  geom_line(aes(y=p_treat_para, linetype="Projection", color="Treatment")) +
  geom_point(aes(y=p_treat_para)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  scale_linetype_manual(values=c("solid", "dashed"), labels=c("Actual", "Projection")) + 
  labs(color = "Group", linetype="Assumption", x="Time(0,1)", y="Probability", title="D")

p1 + p2 + p3 + p4
```


```{r}
# simulate binary outcome
y_binary_before = rbinom(n_control + n_treat, 1, inverse_logit(c(logit_before_untreat, logit_before_treat)))
y_binary_after = rbinom(n_control + n_treat, 1, inverse_logit(c(logit_after_untreat, logit_after_treat)))

df_y_logit = data.frame(treatment = c(rep(0, n_control), rep(1, n_treat), rep(0, n_control), rep(1, n_treat)),
                        time_point = c(rep(0, n_control+n_treat), rep(1, n_control+n_treat)),
                        x = c(unlist(x_binary), unlist(x_binary)),
                        outcome = c(y_binary_before, y_binary_after))

```

## Simulate Count (Poisson) Outcome
$$
\begin{gather*}
Y \sim Poisson (\lambda) \\
\log(\lambda) = \alpha + \gamma G + \delta_t t + \tau D + \beta x + \epsilon \\
\end{gather*}
$$

To simulate outcome, we take the modeled log lambda and sample from Poisson distribution

```{r}
# Binary Timepoint
t = c(0,1)
# Binary Treatment
treatment = c(0,1)
n_control = 1000
n_treat = 300

# simulate X
x_poisson = list(rnorm(n_control, 0, 1), rnorm(n_treat, 0, 1))

# simulate coefficient
alpha_poisson = 0.3# rnorm(1,0,1)
gamma_poisson = 1# rnorm(1,0,1)
delta_t_poisson = -0.5#rnorm(1,0.2,1)
tau_poisson = -0.3#rnorm(1,0.2,1)
beta_poisson = 1# rnorm(1,0,1)

# simulation count
error = rnorm(n_control, 0, 1)
lambda_before_untreat = alpha_poisson + gamma_poisson*treatment[1] + delta_t_poisson*t[1] + 
  tau_poisson*t[1]*treatment[1] + beta_poisson*x_poisson[[1]] + error

error = rnorm(n_treat, 0, 1)
lambda_before_treat = alpha_poisson + gamma_poisson*treatment[2] + delta_t_poisson*t[1] + 
  tau_poisson*t[1]*treatment[2] + beta_poisson*x_poisson[[2]] + error

error = rnorm(n_control, 0, 1)
lambda_after_untreat = alpha_poisson + gamma_poisson*treatment[1] + delta_t_poisson*t[2] + 
  tau_poisson*t[2]*treatment[1] + beta_poisson*x_poisson[[1]] + error

error = rnorm(n_treat, 0, 1)
lambda_after_treat = alpha_poisson + gamma_poisson*treatment[2] + delta_t_poisson*t[2] + 
  tau_poisson*t[2]*treatment[2] + beta_poisson*x_poisson[[2]] + error

lambda_after_treat_para = alpha_poisson + gamma_poisson*treatment[2] + delta_t_poisson*t[2] +
  beta_poisson*x_poisson[[2]] + error
```

```{r}
# visualization
df_log_lambda = data.frame(treatment = c(rep(0, n_control), rep(1, n_treat)),
                      log_lambda_before = c(lambda_before_untreat, lambda_before_treat),
                      log_lambda_after = c(lambda_after_untreat, lambda_after_treat))

p1 = ggplot(df_log_lambda, aes(x=log_lambda_before, color=factor(treatment))) +
  geom_point(aes(y=log_lambda_after)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  labs(color = "Group", x="Log Lambda Before", y="Log Lambda After", title = "A")

df_lambda = data.frame(treatment = c(rep(0, n_control), rep(1, n_treat)),
                      lambda_before = exp(c(lambda_before_untreat, lambda_before_treat)),
                      lambda_after = exp(c(lambda_after_untreat, lambda_after_treat)))

p2 = ggplot(df_lambda, aes(x=lambda_before, color=factor(treatment))) +
  geom_point(aes(y=lambda_after)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  labs(color = "Group", x="Lambda Before", y="Lambda After", title = "B")

df_avg_log_lambda = data.frame(t = t,
                          log_lambda_untreat = c(mean(lambda_before_untreat), mean(lambda_after_untreat)), 
                          log_lambda_treat = c(mean(lambda_before_treat), mean(lambda_after_treat)),
                          log_lambda_treat_para = c(mean(lambda_before_treat), mean(lambda_after_treat_para)))
p3 = ggplot(df_avg_log_lambda, aes(x = t))+
  geom_line(aes(y=log_lambda_untreat, color="Control")) + 
  geom_point(aes(y=log_lambda_untreat)) +
  geom_line(aes(y=log_lambda_treat, linetype="Actual", color="Treatment")) + 
  geom_point(aes(y=log_lambda_treat)) + 
  geom_line(aes(y=log_lambda_treat_para, linetype="Projection", color="Treatment")) +
  geom_point(aes(y=log_lambda_treat_para)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  scale_linetype_manual(values=c("solid", "dashed"), labels=c("Actual", "Projection")) + 
  labs(color = "Group", linetype="Assumption", x="Time(0,1)", y="Log Lambda", title = "C")

df_avg_lambda = data.frame(t = t,
                          lambda_untreat = exp(c(mean(lambda_before_untreat), mean(lambda_after_untreat))), 
                          lambda_treat = exp(c(mean(lambda_before_treat), mean(lambda_after_treat))),
                          lambda_treat_para = exp(c(mean(lambda_before_treat), mean(lambda_after_treat_para))))
p4 = ggplot(df_avg_lambda, aes(x = t))+
  geom_line(aes(y=lambda_untreat, color="Control")) + 
  geom_point(aes(y=lambda_untreat)) +
  geom_line(aes(y=lambda_treat, linetype="Actual", color="Treatment")) + 
  geom_point(aes(y=lambda_treat)) + 
  geom_line(aes(y=lambda_treat_para, linetype="Projection", color="Treatment")) +
  geom_point(aes(y=lambda_treat_para)) + 
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
  scale_linetype_manual(values=c("solid", "dashed"), labels=c("Actual", "Projection")) + 
  labs(color = "Group", linetype="Assumption", x="Time(0,1)", y="Lambda", title = "D")

p1 + p2 + p3 + p4
```

```{r}
# simulate count outcome
y_poisson_before = rpois(n_control + n_treat, exp(c(lambda_before_untreat, lambda_before_treat)))
y_poisson_after = rpois(n_control + n_treat, exp(c(lambda_after_untreat, lambda_after_treat)))

df_y_poisson = data.frame(treatment = c(rep(0, n_control), rep(1, n_treat), rep(0, n_control), rep(1, n_treat)),
                        time_point = c(rep(0, n_control+n_treat), rep(1, n_control+n_treat)),
                        x = c(unlist(x_poisson), unlist(x_poisson)),
                        outcome = c(y_poisson_before, y_poisson_after))
```

# non-parametric DiD
```{r}
non_para_did <- function(df){
  y_1_t1 <- mean(df$outcome[df$treatment == 1 & df$time_point == 1])
  y_1_t0 <- mean(df$outcome[df$treatment == 1 & df$time_point == 0])
  
  y_0_t1 <-  mean(df$outcome[df$treatment == 0 & df$time_point == 1])
  y_0_t0 <-  mean(df$outcome[df$treatment == 0 & df$time_point == 0])
  
  did <- (y_1_t1 - y_1_t0) - (y_0_t1 - y_0_t0)
  
  return (did)
}
```

# non-parametric RiR
```{r}
non_para_rir <- function(df){
  y_1_t1 <- mean(df$outcome[df$treatment == 1 & df$time_point == 1])
  y_1_t0 <- mean(df$outcome[df$treatment == 1 & df$time_point == 0])
  
  y_0_t1 <-  mean(df$outcome[df$treatment == 0 & df$time_point == 1])
  y_0_t0 <-  mean(df$outcome[df$treatment == 0 & df$time_point == 0])
  
  rir <- (y_1_t1 / y_1_t0) / (y_0_t1 / y_0_t0)
  
  return (rir)
}

```

# fitting logistic regression on binary
```{r}
binary_glm = glm(outcome ~ treatment + time_point + x + treatment:time_point, 
                  data=df_y_logit, family="binomial")
binary_true_parameter = c(alpha_binary, gamma_binary, delta_t_binary, beta_binary, tau_binary)
binary_true_parameter
binary_glm$coefficients
p <- fitted(binary_glm)
df_y_logit_outcome <- data.frame(treatment = c(rep(0, n_control), rep(1, n_treat), rep(0, n_control), rep(1, n_treat)),
                        time_point = c(rep(0, n_control+n_treat), rep(1, n_control+n_treat)),
                        x = c(unlist(x_binary), unlist(x_binary)),
                        outcome = p / (1-p))
exp(binary_glm$coefficients[5])
non_para_rir(df_y_logit_outcome)


```



# Poisson Regression
```{r}
poisson_glm = glm(outcome ~ treatment + time_point + x + treatment:time_point, 
                  data=df_y_poisson, family="poisson")
poisson_true_parameter = c(alpha_poisson, gamma_poisson, delta_t_poisson, beta_poisson, tau_poisson)
poisson_true_parameter
poisson_glm$coefficients
exp(poisson_glm$coefficients[5]) 
non_para_rir(df_y_poisson)
```


# Card and Kruger's Parallel Trend Assumption 

```{r, warning = FALSE}
dat <- read_table2('public.dat')
codebook <- read_lines(file = "codebook")

# extract variable name
variable_names <- codebook %>%
  `[`(8:59) %>%
  `[`(-c(5, 6, 13, 14, 32, 33)) %>%
  str_sub(1, 13) %>%
  str_squish() %>%
  str_to_lower()


# match with raw data
dat <- dat %>%
  select(-X47) %>%
  `colnames<-`(., variable_names) %>%
  mutate_all(as.numeric) %>%
  mutate(sheet = as.character(sheet))


# compare before and after outcome
dat <- dat %>% 
  group_by(state) %>% 
  mutate(fte=empft+nmgrs+(0.5*emppt),
         fte_after=empft2+nmgrs2+(0.5*emppt2)) 


summary <- dat %>% group_by(state) %>% 
            summarise(mean_before=mean(fte,na.rm=T),
                      mean_after=mean(fte_after,na.rm=T),
                      var_before=var(fte,na.rm=T),
                      var_after=var(fte_after,na.rm=T),
                      count_before=sum(!is.na(fte)),
                      count_after=sum(!is.na(fte_after))) %>%
           ungroup() %>%
           mutate(se_before=sqrt(var_before/count_before),
                  se_after=sqrt(var_after/count_after)) %>%
          mutate(state=ifelse(state==0,"PA","NJ")) 


# treatment and control average unemployment
unemployment_df <- dat %>%
  select(state, fte, fte_after)

unemployment_df <- na.omit(unemployment_df) %>%
  

unemployment_df_expand <- gather(unemployment_df, 
                                 time, 
                                 obs_unemployment, 
                                 fte:fte_after, 
                                 factor_key = TRUE) %>%
  mutate(time = ifelse(time == "fte", 0, 1)) %>%
  mutate(state = ifelse(state == 0, "PA", "NJ"))

# p1 = ggplot(unemployment_df, aes(x=fte_after, color = factor(state))) +
#   geom_point(aes(y=fte_after)) + 
#   scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) + 
#   labs(color = "Group", x="Unemployment Before", y="Unemployment After", title="B")

mean_unemployment <- unemployment_df_expand %>%
  group_by(time, state) %>% 
  summarise(mean_unemployment = mean(obs_unemployment))

# wide to long format 
# plot_df_2 <- gather(mean_unemployment, 
#                     time, 
#                     obs_unemployment, 
#                     mean_before:mean_after, 
#                     factor_key = TRUE) 


plot_df_2 <- data.frame(t = c(0, 1), 
                        unemployment_treated = c(20.4, 20.9), 
                        unemployment_control = c(23.1, 21.1), 
                        unemployment_projected = c(20.4, 18.5))


card_parallel = ggplot(plot_df_2, aes(x = t))+
  geom_line(aes(y=unemployment_control, color="Control")) +
  geom_point(aes(y=unemployment_control)) +
  geom_line(aes(y=unemployment_treated, linetype="Actual", color="Treatment")) +
  geom_point(aes(y=unemployment_treated)) +
  geom_line(aes(y=unemployment_projected, linetype="Projection", color="Treatment")) +
  geom_point(aes(y=unemployment_projected)) +
  scale_color_manual(values=c("black", "red"), labels=c("Control", "Treatment")) +
  scale_linetype_manual(values=c("solid", "dashed"), labels=c("Actual", "Projection")) +
  labs(color = "Group", linetype="Assumption", x="Time(0,1)", y="Unemployment")
card_parallel


```


# Regression Perspective 
```{r}
dat_regression <- gather(dat, 
                    time, 
                    unemployment, 
                    fte:fte_after, 
                    factor_key = TRUE) 

dat_regression <- dat_regression %>%
  mutate(time = ifelse(time == 'fte', 0, 1)) %>%
  select(state, time, unemployment)

# unparametric did 
colnames(dat_regression) <- c("treatment", "time_point", "outcome")
non_para_did(dat_regression)

# fitting linear regression 
linear_minum_wage <- lm(unemployment ~ state + time + state * time, 
                        data = dat_regression)
summary(linear_minum_wage)
```




